name: pokedex
description: A new Flutter project.



publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  dio: ^4.0.4
  dartz: ^0.10.1
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  flutter_native_splash: ^2.0.4
  percent_indicator: ^4.0.0
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  modular_test: ^1.0.1+1
  build_runner: ^2.1.7
  


flutter:

  
  
  
  uses-material-design: true

  
  assets:
  - assets/images/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
